package com.daltao.script.token.impl;

import lombok.Getter;

@Getter
public enum TokenType {
    NOP, SEMICOLON, EOL, STRING, IDENTIFIER, LOGICAL_EQUAL, LOGICAL_LS, LOGICAL_LEQ, LOGICAL_GT, LOGICAL_GEQ,
    INT, WHILE, IF, ELSE, LEFT_CURLY_BRACKET, RIGHT_CURLY_BRACKET, EQUAL, LOGICAL_AND, LOGICAL_OR, LOGICAL_NOT,
    TWO_OPERAND_OPERATOR, COMMENT, EOF, TEXT
    ;

}
